### PR TITLE
Update sidebar.user.js

### PR DESCRIPTION
**Pull request by Aaahh**
This commit actually has use.

### CODE REVIEW

**Comment by Aaahh** [comment]
I actually fix a bug...

**Comment by JuanPotato** [comment]
I see not bug fix :tongue:

**Comment by Aaahh** [comment]
There is!!!! Your script runs on all oneplus websites, not just the fourms

**Comment by JuanPotato** [comment]
lol dats fine
I've noticed it before but never said anything

**Comment by Aaahh** [comment]
MERGE IT

**Comment by JuanPotato** [comment]
still no bug

**Pull request closed without merging**
